//
//  Store.swift
//  Lucent
//
//  Created by Steven Grosmark on 3/6/26.
//

import Foundation
import Evident


/// Base class for screen-specific stores.
///
/// - Holds the screen `State`
/// - All `Action` events are handled in the subclass override of `handleAction`
///
@MainActor
open class Store<Screen: ScreenDefinition> {

    public typealias State = Screen.State
    public typealias Action = Screen.Action
    public typealias Output = Screen.Output

    private var state: State
    private let actions: MessageQueue<Action>
    private let outputs: MessageQueue<Output>

    public private(set) lazy var viewModel: ViewModel<Screen> = {
        let stateProjection = Screen.viewStateProjection
        let viewActionToScreenAction = Screen.toAction
        return ViewModel<Screen>(
            state: stateProjection.toViewState(state),
            sendAction: { [weak self] action in
                self?.actions.dispatch(viewActionToScreenAction(action))
            },
            sendState: { @MainActor [weak self] viewState in
                guard let self else { return }
                self.state = stateProjection.toState(viewState, self.state)
            }
        )
    }()

    public init(state: State) {
        self.state = state
        self.actions = MessageQueue<Action>()
        self.outputs = MessageQueue<Output>()

        actions.observe { [weak self] action in
            await self?.routeAction(action)
        }

        setUpViewStateObservation(
            viewState: ViewStateObservation(viewModel: viewModel)
        )
    }

    /// Observe outputs emitted by the screen
    public func observe(outputHandler: @escaping @MainActor @Sendable (Output) async -> Void) {
        outputs.observe(outputHandler)
    }

    /// Opportunity for a `Store` subclass to observe `ViewState` changes that happen in the view.
    open func setUpViewStateObservation(viewState: ViewStateObservation<Screen>) {

    }

    /// Respond to an incoming `Action`.
    ///
    /// Subclasses must override this to handle incoming actions from the view layer.
    ///
    /// - Parameters:
    ///   - action: The action generated by a view, or side effect.
    ///   - state: The current, mutable state.
    ///   - store: Provides the ability to start a side-effect and/or emit some output.
    open func handleAction(action: Action, state: inout State, store: StoreAccess) {
        fatalError("handleAction must be overridden")
    }

    // MARK: - Implementation details

    /// Helper to provide limited access for sending actions
    public struct ActionAccess: Sendable {
        public let send: @Sendable (Action) async -> Void

        init(send: @escaping @Sendable (Action) async -> Void) {
            self.send = send
        }
    }

    /// Helper to provide limited access for sending outputs and running side effects
    public struct StoreAccess: Sendable {
        public let sendOutput: @Sendable (Output) -> Void
        public let runSideEffect: @Sendable (@escaping @Sendable (ActionAccess) async -> Void) -> Void

        init(
            sendOutput: @escaping @Sendable (Output) -> Void,
            runSideEffect: @escaping @Sendable (@Sendable @escaping (ActionAccess) async -> Void) -> Void
        ) {
            self.sendOutput = sendOutput
            self.runSideEffect = runSideEffect
        }
    }

    /// Internal action handler. Creates the reduced access helpers and calls `handleAction`.
    private func routeAction(_ action: Action) async {
        let store = StoreAccess(
            sendOutput: outputs.dispatch(_:),
            runSideEffect: { [weak self] effect in
                Task {
                    await self?.enqueueSideEffect(effect)
                }
            }
        )
        var state = state
        self.handleAction(action: action, state: &state, store: store)
        self.state = state
        self.viewModel.state = Screen.viewStateProjection.toViewState(state)
    }

    // NOTE: This should also keep track of the side effects, for cancellation / testing purposes.
    // For now, this just spawns a background Task to run the effect.

    /// Runs a side effect. Side effects can **only** emit actions, and have no access to state or outputs.
    private func enqueueSideEffect(_ effect: @escaping @Sendable (ActionAccess) async -> Void) {
        let actions = ActionAccess(
            send: { [weak self] action in
                self?.actions.dispatch(action)
            }
        )
        Task {
            await effect(actions)
        }
    }
}
